# Generated by Django 3.0.5 on 2020-10-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('semail', models.EmailField(max_length=254)),
                ('sphone_no', models.IntegerField()),
                ('saddress', models.CharField(max_length=50)),
            ],
        ),
    ]
